apiVersion: v1
kind: Service
metadata:
  name: cedar-summit
  labels:
    app: cedar-summit
spec:
  type: ClusterIP
  selector:
    app: cedar-summit
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
